services:
  nestjs_app:
    build: .
    container_name: nestjs_app
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_NAME=dormitory_db
      - JWT_SECRET=0yFH+KgskOYKmG/+7pC8btfeBYFZaESsBECuTE7YVmY=
      - KAKAO_CLIENT_ID=3690a2db2a794b9c48ee834b2ba49890
      - KAKAO_CALLBACK_URL=http://localhost:3000/auth/kakao/callback
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mysql
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - nestjs_app
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dormitory_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  mysql_data:
